CREATE SCHEMA alpha_vantage_db
    AUTHORIZATION postgres;

CREATE TABLE alpha_vantage_db.stock (
    stock_id SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ticker VARCHAR(10) NOT NULL
);

ALTER TABLE alpha_vantage_db.stock 
ADD CONSTRAINT unique_ticker UNIQUE (ticker);

INSERT INTO alpha_vantage_db.stock (ticker) 
    VALUES 
    ('APPL'),
    ('TSLA'),
    ('MSFT'),
    ('GOOG');

CREATE TABLE alpha_vantage_db.currency (
    currency_id SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    currency_name VARCHAR(10) NOT NULL
);

INSERT INTO alpha_vantage_db.currency (currency_name) 
    VALUES 
    ('USD');


CREATE TABLE alpha_vantage_db.overview (
    -- Identification & Foreign Keys (Now Auto-Incrementing)
    stock_id SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    currency_id SMALLINT NOT NULL,
    
    -- General Info
    asset_type VARCHAR(50),
    name VARCHAR(255),
    description TEXT,
    cik VARCHAR(20),
    exchange VARCHAR(100),
    country VARCHAR(100),
    sector VARCHAR(100),
    industry VARCHAR(255),
    address TEXT,
    official_site VARCHAR(255),
    
    -- Financial Calendar
    fiscal_year_end VARCHAR(20),
    latest_quarter DATE,
    
    -- Market Data
    market_capitalization BIGINT,
    ebitda BIGINT,
    revenue_ttm BIGINT,
    gross_profit_ttm BIGINT,
    
    -- Valuation Ratios
    pe_ratio DECIMAL(15, 4),
    peg_ratio DECIMAL(15, 4),
    book_value DECIMAL(15, 4),
    dividend_per_share DECIMAL(15, 4),
    dividend_yield DECIMAL(15, 4),
    eps DECIMAL(15, 4),
    revenue_per_share_ttm DECIMAL(15, 4),
    profit_margin DECIMAL(15, 4),
    operating_margin_ttm DECIMAL(15, 4),
    return_on_assets_ttm DECIMAL(15, 4),
    return_on_equity_ttm DECIMAL(15, 4),
    diluted_eps_ttm DECIMAL(15, 4),
    
    -- Growth Metrics
    quarterly_earnings_growth_yoy DECIMAL(15, 4),
    quarterly_revenue_growth_yoy DECIMAL(15, 4),
    
    -- Analyst Metrics
    analyst_target_price DECIMAL(15, 4),
    analyst_rating_strong_buy INT,
    analyst_rating_buy INT,
    analyst_rating_hold INT,
    analyst_rating_sell INT,
    analyst_rating_strong_sell INT,
    
    -- Price Metrics
    trailing_pe DECIMAL(15, 4),
    forward_pe DECIMAL(15, 4),
    price_to_sales_ratio_ttm DECIMAL(15, 4),
    price_to_book_ratio DECIMAL(15, 4),
    ev_to_revenue DECIMAL(15, 4),
    ev_to_ebitda DECIMAL(15, 4),
    beta DECIMAL(15, 4),
    high_52_week DECIMAL(15, 4),
    low_52_week DECIMAL(15, 4),
    moving_average_50_day DECIMAL(15, 4),
    moving_average_200_day DECIMAL(15, 4),
    
    -- Share Statistics
    shares_outstanding BIGINT,
    shares_float BIGINT,
    percent_insiders DECIMAL(15, 4),
    percent_institutions DECIMAL(15, 4),
    
    -- Dividends
    dividend_date DATE,
    ex_dividend_date DATE,

    -- Table Constraints
    CONSTRAINT fk_stock FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE,
    CONSTRAINT fk_currency FOREIGN KEY (currency_id) REFERENCES alpha_vantage_db.currency(currency_id)
);

COPY alpha_vantage_db.overview 
    (   
        asset_type, name, description, cik, exchange, 
        currency_id, country, sector, industry, address, official_site, 
        fiscal_year_end, latest_quarter, market_capitalization, ebitda, 
        pe_ratio, peg_ratio, book_value, dividend_per_share, dividend_yield, 
        eps, revenue_per_share_ttm, profit_margin, operating_margin_ttm, 
        return_on_assets_ttm, return_on_equity_ttm, revenue_ttm, gross_profit_ttm, 
        diluted_eps_ttm, quarterly_earnings_growth_yoy, quarterly_revenue_growth_yoy, 
        analyst_target_price, analyst_rating_strong_buy, analyst_rating_buy, 
        analyst_rating_hold, analyst_rating_sell, analyst_rating_strong_sell, 
        trailing_pe, forward_pe, price_to_sales_ratio_ttm, price_to_book_ratio, 
        ev_to_revenue, ev_to_ebitda, beta, high_52_week, low_52_week, 
        moving_average_50_day, moving_average_200_day, shares_outstanding, 
        shares_float, percent_insiders, percent_institutions, dividend_date, 
        ex_dividend_date
    )
FROM '/tmp/overview.csv' DELIMITER ',' CSV HEADER;

-- Creating and populating shares_outstanding table
CREATE TABLE alpha_vantage_db.shares_outstanding (
    stock_id SMALLINT REFERENCES alpha_vantage_db.stock(stock_id),
    date DATE,
    shares_outstanding_diluted BIGINT,
    shares_outstanding_basic BIGINT,
    -- This creates the composite primary key
    PRIMARY KEY (stock_id, date)
);

COPY alpha_vantage_db.shares_outstanding
    (   
            date,
            shares_outstanding_diluted,
            shares_outstanding_basic,
            stock_id
    )
FROM '/tmp/shares_outstanding.csv' DELIMITER ',' CSV HEADER;

-- Creating and populating earnings table
CREATE TABLE alpha_vantage_db.earnings (
    stock_id SMALLINT REFERENCES alpha_vantage_db.stock(stock_id),
    fiscal_date_ending DATE,
    reported_eps DECIMAL(10,2),
    -- This creates the composite primary key
    PRIMARY KEY (stock_id, fiscal_date_ending )
);

COPY alpha_vantage_db.earnings
    (   
            fiscal_date_ending,
            reported_eps,
            stock_id
    )
FROM '/tmp/earnings.csv' DELIMITER ',' CSV HEADER;

-- Creating and populating dividends table
CREATE TABLE alpha_vantage_db.dividends (
    stock_id SMALLINT REFERENCES alpha_vantage_db.stock(stock_id),
    ex_dividend_date DATE,
    declaration_date DATE,
    record_date DATE,
    payment_date DATE,
    amount DECIMAL(5,2),
    -- This creates the composite primary key
    PRIMARY KEY (stock_id, ex_dividend_date)
);

COPY alpha_vantage_db.dividends 
    (
        ex_dividend_date,
        declaration_date,
        record_date,
        payment_date,
        amount,
        stock_id
    )
FROM '/tmp/dividends.csv' DELIMITER ',' CSV HEADER;

-- Creating and populating dividends table
CREATE TABLE alpha_vantage_db.splits (
    stock_id SMALLINT REFERENCES alpha_vantage_db.stock(stock_id),
    effective_date DATE,
    split_factor DECIMAL(4,2),
    -- This creates the composite primary key
    PRIMARY KEY (stock_id, effective_date)
);

COPY alpha_vantage_db.splits
    (
        effective_date,
        split_factor,
        stock_id
    )
FROM '/tmp/splits.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE alpha_vantage_db.income_statement (
    stock_id SMALLINT,
    fiscal_date_ending DATE,
    reported_currency VARCHAR(3),
    gross_profit DECIMAL(19,4),
    total_revenue DECIMAL(19,4),
    cost_of_revenue DECIMAL(19,4),
    cost_of_goods_and_services_sold DECIMAL(19,4),
    operating_income DECIMAL(19,4),
    selling_general_and_administrative DECIMAL(19,4),
    research_and_development DECIMAL(19,4),
    operating_expenses DECIMAL(19,4),
    investment_income_net DECIMAL(19,4),
    net_interest_income DECIMAL(19,4),
    interest_income DECIMAL(19,4),
    interest_expense DECIMAL(19,4),
    non_interest_income DECIMAL(19,4),
    other_non_operating_income DECIMAL(19,4),
    depreciation DECIMAL(19,4),
    depreciation_and_amortization DECIMAL(19,4),
    income_before_tax DECIMAL(19,4),
    income_tax_expense DECIMAL(19,4),
    interest_and_debt_expense DECIMAL(19,4),
    net_income_from_continuing_operations DECIMAL(19,4),
    comprehensive_income_net_of_tax DECIMAL(19,4),
    ebit DECIMAL(19,4),
    ebitda DECIMAL(19,4),
    net_income DECIMAL(19,4),
    
    -- Constraints
    PRIMARY KEY (stock_id, fiscal_date_ending),
    CONSTRAINT fk_income_stock FOREIGN KEY (stock_id) 
        REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE
);


COPY alpha_vantage_db.income_statement
    (
        fiscal_date_ending,
        reported_currency,
        gross_profit,
        total_revenue,
        cost_of_revenue,
        cost_of_goods_and_services_sold,
        operating_income,
        selling_general_and_administrative,
        research_and_development,
        operating_expenses,
        investment_income_net,
        net_interest_income,
        interest_income,
        interest_expense,
        non_interest_income,
        other_non_operating_income,
        depreciation,
        depreciation_and_amortization,
        income_before_tax,
        income_tax_expense,
        interest_and_debt_expense,
        net_income_from_continuing_operations,
        comprehensive_income_net_of_tax,
        ebit,
        ebitda,
        net_income,
        stock_id
    )
FROM '/tmp/google_income.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE alpha_vantage_db.balance_sheet (
    -- Identification
    stock_id SMALLINT,
    fiscal_date_ending DATE,
    reported_currency VARCHAR(3),

    -- Assets
    total_assets DECIMAL(19,4),
    total_current_assets DECIMAL(19,4),
    cash_and_cash_equivalents_at_carrying_value DECIMAL(19,4),
    cash_and_short_term_investments DECIMAL(19,4),
    inventory DECIMAL(19,4),
    current_net_receivables DECIMAL(19,4),
    total_non_current_assets DECIMAL(19,4),
    property_plant_equipment DECIMAL(19,4),
    accumulated_depreciation_amortization_ppe DECIMAL(19,4),
    intangible_assets DECIMAL(19,4),
    intangible_assets_excluding_goodwill DECIMAL(19,4),
    goodwill DECIMAL(19,4),
    investments DECIMAL(19,4),
    long_term_investments DECIMAL(19,4),
    short_term_investments DECIMAL(19,4),
    other_current_assets DECIMAL(19,4),
    other_non_current_assets DECIMAL(19,4),

    -- Liabilities
    total_liabilities DECIMAL(19,4),
    total_current_liabilities DECIMAL(19,4),
    current_accounts_payable DECIMAL(19,4),
    deferred_revenue DECIMAL(19,4),
    current_debt DECIMAL(19,4),
    short_term_debt DECIMAL(19,4),
    total_non_current_liabilities DECIMAL(19,4),
    capital_lease_obligations DECIMAL(19,4),
    long_term_debt DECIMAL(19,4),
    current_long_term_debt DECIMAL(19,4),
    long_term_debt_noncurrent DECIMAL(19,4),
    short_long_term_debt_total DECIMAL(19,4),
    other_current_liabilities DECIMAL(19,4),
    other_non_current_liabilities DECIMAL(19,4),

    -- Equity & Shares
    total_shareholder_equity DECIMAL(19,4),
    treasury_stock DECIMAL(19,4),
    retained_earnings DECIMAL(19,4),
    common_stock DECIMAL(19,4),
    common_stock_shares_outstanding BIGINT,

    -- Constraints
    PRIMARY KEY (stock_id, fiscal_date_ending),
    CONSTRAINT fk_balance_stock FOREIGN KEY (stock_id) 
        REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE
);

-- STEP 1: Break the dependencies by dropping the foreign keys on Income and Cash Flow
ALTER TABLE alpha_vantage_db.income_statement DROP CONSTRAINT fk_income_to_balance;
ALTER TABLE alpha_vantage_db.cash_flow DROP CONSTRAINT fk_cashflow_to_balance;


-- STEP 2: Upgrade the BALANCE SHEET table structure
ALTER TABLE alpha_vantage_db.balance_sheet DROP CONSTRAINT balance_sheet_pkey;
ALTER TABLE alpha_vantage_db.balance_sheet ADD COLUMN report_type VARCHAR(10) NOT NULL DEFAULT 'ANNUAL';
ALTER TABLE alpha_vantage_db.balance_sheet ADD CONSTRAINT pk_balance_sheet PRIMARY KEY (stock_id, fiscal_date_ending, report_type);
ALTER TABLE alpha_vantage_db.balance_sheet ALTER COLUMN report_type DROP DEFAULT;


-- STEP 3: Upgrade the INCOME STATEMENT table structure
-- (Assuming its old PK was also stock_id + fiscal_date_ending)
ALTER TABLE alpha_vantage_db.income_statement DROP CONSTRAINT income_statement_pkey;
ALTER TABLE alpha_vantage_db.income_statement ADD COLUMN report_type VARCHAR(10) NOT NULL DEFAULT 'ANNUAL';
ALTER TABLE alpha_vantage_db.income_statement ADD CONSTRAINT pk_income_statement PRIMARY KEY (stock_id, fiscal_date_ending, report_type);
ALTER TABLE alpha_vantage_db.income_statement ALTER COLUMN report_type DROP DEFAULT;


-- STEP 4: Upgrade the CASH FLOW table structure
-- (Assuming its old PK was also stock_id + fiscal_date_ending)
ALTER TABLE alpha_vantage_db.cash_flow DROP CONSTRAINT cash_flow_pkey;
ALTER TABLE alpha_vantage_db.cash_flow ADD COLUMN report_type VARCHAR(10) NOT NULL DEFAULT 'ANNUAL';
ALTER TABLE alpha_vantage_db.cash_flow ADD CONSTRAINT pk_cash_flow PRIMARY KEY (stock_id, fiscal_date_ending, report_type);
ALTER TABLE alpha_vantage_db.cash_flow ALTER COLUMN report_type DROP DEFAULT;


-- STEP 5: Re-link the foreign keys using the updated 3-column relationship
ALTER TABLE alpha_vantage_db.income_statement 
    ADD CONSTRAINT fk_income_to_balance 
    FOREIGN KEY (stock_id, fiscal_date_ending, report_type) 
    REFERENCES alpha_vantage_db.balance_sheet (stock_id, fiscal_date_ending, report_type) 
    ON DELETE CASCADE;

ALTER TABLE alpha_vantage_db.cash_flow 
    ADD CONSTRAINT fk_cashflow_to_balance 
    FOREIGN KEY (stock_id, fiscal_date_ending, report_type) 
    REFERENCES alpha_vantage_db.balance_sheet (stock_id, fiscal_date_ending, report_type) 
    ON DELETE CASCADE;



COPY alpha_vantage_db.balance_sheet
    (
        fiscal_date_ending,
        reported_currency,
        total_assets,
        total_current_assets,
        cash_and_cash_equivalents_at_carrying_value,
        cash_and_short_term_investments,
        inventory,
        current_net_receivables,
        total_non_current_assets,
        property_plant_equipment,
        accumulated_depreciation_amortization_ppe,
        intangible_assets,
        intangible_assets_excluding_goodwill,
        goodwill,
        investments,
        long_term_investments,
        short_term_investments,
        other_current_assets,
        other_non_current_assets,
        total_liabilities,
        total_current_liabilities,
        current_accounts_payable,
        deferred_revenue,
        current_debt,
        short_term_debt,
        total_non_current_liabilities,
        capital_lease_obligations,
        long_term_debt,
        current_long_term_debt,
        long_term_debt_noncurrent,
        short_long_term_debt_total,
        other_current_liabilities,
        other_non_current_liabilities,
        total_shareholder_equity,
        treasury_stock,
        retained_earnings,
        common_stock,
        common_stock_shares_outstanding,
        stock_id
    )
FROM '/tmp/google_balance.csv' 
DELIMITER ',' 
CSV HEADER;

CREATE TABLE alpha_vantage_db.cash_flow (
    stock_id SMALLINT,
    fiscal_date_ending DATE,
    reported_currency VARCHAR(3),
    operating_cashflow DECIMAL(19,4),
    payments_for_operating_activities DECIMAL(19,4),
    proceeds_from_operating_activities DECIMAL(19,4),
    change_in_operating_liabilities DECIMAL(19,4),
    change_in_operating_assets DECIMAL(19,4),
    depreciation_depletion_and_amortization DECIMAL(19,4),
    capital_expenditures DECIMAL(19,4),
    change_in_receivables DECIMAL(19,4),
    change_in_inventory DECIMAL(19,4),
    profit_loss DECIMAL(19,4),
    cashflow_from_investment DECIMAL(19,4),
    cashflow_from_financing DECIMAL(19,4),
    proceeds_from_repayments_of_short_term_debt DECIMAL(19,4),
    payments_for_repurchase_of_common_stock DECIMAL(19,4),
    payments_for_repurchase_of_equity DECIMAL(19,4),
    payments_for_repurchase_of_preferred_stock DECIMAL(19,4),
    dividend_payout DECIMAL(19,4),
    dividend_payout_common_stock DECIMAL(19,4),
    dividend_payout_preferred_stock DECIMAL(19,4),
    proceeds_from_issuance_of_common_stock DECIMAL(19,4),
    proceeds_from_issuance_of_long_term_debt_and_capital_securities DECIMAL(19,4),
    proceeds_from_issuance_of_preferred_stock DECIMAL(19,4),
    proceeds_from_repurchase_of_equity DECIMAL(19,4),
    proceeds_from_sale_of_treasury_stock DECIMAL(19,4),
    stock_based_compensation DECIMAL(19,4),
    change_in_cash_and_cash_equivalents DECIMAL(19,4),
    change_in_exchange_rate DECIMAL(19,4),
    net_income DECIMAL(19,4),

    -- Constraints
    PRIMARY KEY (stock_id, fiscal_date_ending),
    CONSTRAINT fk_cashflow_stock FOREIGN KEY (stock_id) 
        REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE
);


COPY alpha_vantage_db.cash_flow
    (
        fiscal_date_ending,
        reported_currency,
        operating_cashflow,
        payments_for_operating_activities,
        proceeds_from_operating_activities,
        change_in_operating_liabilities,
        change_in_operating_assets,
        depreciation_depletion_and_amortization,
        capital_expenditures,
        change_in_receivables,
        change_in_inventory,
        profit_loss,
        cashflow_from_investment,
        cashflow_from_financing,
        proceeds_from_repayments_of_short_term_debt,
        payments_for_repurchase_of_common_stock,
        payments_for_repurchase_of_equity,
        payments_for_repurchase_of_preferred_stock,
        dividend_payout,
        dividend_payout_common_stock,
        dividend_payout_preferred_stock,
        proceeds_from_issuance_of_common_stock,
        proceeds_from_issuance_of_long_term_debt_and_capital_securities,
        proceeds_from_issuance_of_preferred_stock,
        proceeds_from_repurchase_of_equity,
        proceeds_from_sale_of_treasury_stock,
        stock_based_compensation,
        change_in_cash_and_cash_equivalents,
        change_in_exchange_rate,
        net_income,
        stock_id
    )
FROM '/tmp/cash_flow.csv' 
DELIMITER ',' 
CSV HEADER 
NULL '';


CREATE TABLE alpha_vantage_db.earnings_estimates (
    stock_id SMALLINT,
    date DATE,
    horizon VARCHAR(50),
    eps_estimate_average DECIMAL(19,4),
    eps_estimate_high DECIMAL(19,4),
    eps_estimate_low DECIMAL(19,4),
    eps_estimate_analyst_count INT,
    eps_estimate_average_7_days_ago DECIMAL(19,4),
    eps_estimate_average_30_days_ago DECIMAL(19,4),
    eps_estimate_average_60_days_ago DECIMAL(19,4),
    eps_estimate_average_90_days_ago DECIMAL(19,4),
    eps_estimate_revision_up_trailing_7_days INT,
    eps_estimate_revision_down_trailing_7_days INT,
    eps_estimate_revision_up_trailing_30_days INT,
    eps_estimate_revision_down_trailing_30_days INT,
    revenue_estimate_average DECIMAL(25,2),
    revenue_estimate_high DECIMAL(25,2),
    revenue_estimate_low DECIMAL(25,2),
    revenue_estimate_analyst_count INT,

    -- Constraints
    PRIMARY KEY (stock_id, date, horizon),
    CONSTRAINT fk_estimates_stock FOREIGN KEY (stock_id) 
        REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE
);

ALTER TABLE alpha_vantage_db.earnings_estimates 
    ALTER COLUMN eps_estimate_analyst_count TYPE DECIMAL(19,2),
    ALTER COLUMN eps_estimate_revision_up_trailing_7_days TYPE DECIMAL(19,2),
    ALTER COLUMN eps_estimate_revision_down_trailing_7_days TYPE DECIMAL(19,2),
    ALTER COLUMN eps_estimate_revision_up_trailing_30_days TYPE DECIMAL(19,2),
    ALTER COLUMN eps_estimate_revision_down_trailing_30_days TYPE DECIMAL(19,2),
    ALTER COLUMN revenue_estimate_analyst_count TYPE DECIMAL(19,2);


COPY alpha_vantage_db.earnings_estimates
    (
        date,
        horizon,
        eps_estimate_average,
        eps_estimate_high,
        eps_estimate_low,
        eps_estimate_analyst_count,
        eps_estimate_average_7_days_ago,
        eps_estimate_average_30_days_ago,
        eps_estimate_average_60_days_ago,
        eps_estimate_average_90_days_ago,
        eps_estimate_revision_up_trailing_7_days,
        eps_estimate_revision_down_trailing_7_days,
        eps_estimate_revision_up_trailing_30_days,
        eps_estimate_revision_down_trailing_30_days,
        revenue_estimate_average,
        revenue_estimate_high,
        revenue_estimate_low,
        revenue_estimate_analyst_count,
        stock_id
    )
FROM '/tmp/earnings_estimates.csv' 
DELIMITER ',' 
CSV HEADER 
NULL '';

-- Alter the tables to add foreign key constraints to income and cash flow statement
ALTER TABLE alpha_vantage_db.income_statement
ADD CONSTRAINT fk_income_to_balance 
FOREIGN KEY (stock_id, fiscal_date_ending) 
REFERENCES alpha_vantage_db.balance_sheet (stock_id, fiscal_date_ending)
ON DELETE CASCADE; -- Optional: cleans up income records if balance sheet is deleted

ALTER TABLE alpha_vantage_db.cash_flow
ADD CONSTRAINT fk_cashflow_to_balance 
FOREIGN KEY (stock_id, fiscal_date_ending) 
REFERENCES alpha_vantage_db.balance_sheet (stock_id, fiscal_date_ending)
ON DELETE CASCADE;

-- Drop Foreign Keys from child tables
ALTER TABLE alpha_vantage_db.overview DROP CONSTRAINT IF EXISTS fk_stock;
ALTER TABLE alpha_vantage_db.overview DROP CONSTRAINT IF EXISTS fk_currency;
ALTER TABLE alpha_vantage_db.shares_outstanding DROP CONSTRAINT IF EXISTS shares_outstanding_stock_id_fkey;
ALTER TABLE alpha_vantage_db.earnings DROP CONSTRAINT IF EXISTS earnings_stock_id_fkey;
ALTER TABLE alpha_vantage_db.dividends DROP CONSTRAINT IF EXISTS dividends_stock_id_fkey;
ALTER TABLE alpha_vantage_db.splits DROP CONSTRAINT IF EXISTS splits_stock_id_fkey;
ALTER TABLE alpha_vantage_db.income_statement DROP CONSTRAINT IF EXISTS fk_income_stock;
ALTER TABLE alpha_vantage_db.balance_sheet DROP CONSTRAINT IF EXISTS fk_balance_stock;
ALTER TABLE alpha_vantage_db.cash_flow DROP CONSTRAINT IF EXISTS fk_cashflow_stock;
ALTER TABLE alpha_vantage_db.earnings_estimates DROP CONSTRAINT IF EXISTS ffk_estimates_stock;

-- Parent Tables
ALTER TABLE alpha_vantage_db.stock ALTER COLUMN stock_id TYPE SMALLINT;
ALTER TABLE alpha_vantage_db.currency ALTER COLUMN currency_id TYPE SMALLINT;

-- Child Tables (Existing)
ALTER TABLE alpha_vantage_db.overview ALTER COLUMN stock_id TYPE SMALLINT;
ALTER TABLE alpha_vantage_db.overview ALTER COLUMN currency_id TYPE SMALLINT;
ALTER TABLE alpha_vantage_db.shares_outstanding ALTER COLUMN stock_id TYPE SMALLINT;
ALTER TABLE alpha_vantage_db.earnings ALTER COLUMN stock_id TYPE SMALLINT;
ALTER TABLE alpha_vantage_db.dividends ALTER COLUMN stock_id TYPE SMALLINT;
ALTER TABLE alpha_vantage_db.splits ALTER COLUMN stock_id TYPE SMALLINT;
ALTER TABLE alpha_vantage_db.income_statement ALTER COLUMN stock_id TYPE SMALLINT;

-- Child Tables (Added)
ALTER TABLE alpha_vantage_db.balance_sheet ALTER COLUMN stock_id TYPE SMALLINT;
ALTER TABLE alpha_vantage_db.cash_flow ALTER COLUMN stock_id TYPE SMALLINT;
ALTER TABLE alpha_vantage_db.earnings_estimates ALTER COLUMN stock_id TYPE SMALLINT;

-- Overview
ALTER TABLE alpha_vantage_db.overview 
    ADD CONSTRAINT fk_stock FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_currency FOREIGN KEY (currency_id) REFERENCES alpha_vantage_db.currency(currency_id);

-- Standard Financials
ALTER TABLE alpha_vantage_db.shares_outstanding ADD CONSTRAINT fk_stock_shares FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE;
ALTER TABLE alpha_vantage_db.earnings ADD CONSTRAINT fk_stock_earnings FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE;
ALTER TABLE alpha_vantage_db.dividends ADD CONSTRAINT fk_stock_dividends FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE;
ALTER TABLE alpha_vantage_db.splits ADD CONSTRAINT fk_stock_splits FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE;

-- Statements & Estimates
ALTER TABLE alpha_vantage_db.income_statement ADD CONSTRAINT fk_income_stock FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE;
ALTER TABLE alpha_vantage_db.balance_sheet ADD CONSTRAINT fk_balance_stock FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE;
ALTER TABLE alpha_vantage_db.cash_flow ADD CONSTRAINT fk_cashflow_stock FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE;
ALTER TABLE alpha_vantage_db.earnings_estimates ADD CONSTRAINT fk_estimates_stock FOREIGN KEY (stock_id) REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE;


-- Creating and populating shares_outstanding table
CREATE TABLE alpha_vantage_db.ohlcv (
    stock_id SMALLINT REFERENCES alpha_vantage_db.stock(stock_id),
    open NUMERIC(12,4),
    high NUMERIC(12,4),
    low NUMERIC(12,4),   -- Added comma
    close NUMERIC(12,4),
    volume BIGINT,
    date DATE,
    year SMALLINT,
    -- 'year' MUST be included here because it is the partition key
    PRIMARY KEY (stock_id, date, year) 
)
PARTITION BY RANGE (year);

CREATE TABLE alpha_vantage_db.ohlcv_2000 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2000) TO (2001);
CREATE TABLE alpha_vantage_db.ohlcv_2001 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2001) TO (2002);
CREATE TABLE alpha_vantage_db.ohlcv_2002 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2002) TO (2003);
CREATE TABLE alpha_vantage_db.ohlcv_2003 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2003) TO (2004);
CREATE TABLE alpha_vantage_db.ohlcv_2004 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2004) TO (2005);
CREATE TABLE alpha_vantage_db.ohlcv_2005 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2005) TO (2006);
CREATE TABLE alpha_vantage_db.ohlcv_2006 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2006) TO (2007);
CREATE TABLE alpha_vantage_db.ohlcv_2007 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2007) TO (2008);
CREATE TABLE alpha_vantage_db.ohlcv_2008 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2008) TO (2009);
CREATE TABLE alpha_vantage_db.ohlcv_2009 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2009) TO (2010);
CREATE TABLE alpha_vantage_db.ohlcv_2010 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2010) TO (2011);
CREATE TABLE alpha_vantage_db.ohlcv_2011 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2011) TO (2012);
CREATE TABLE alpha_vantage_db.ohlcv_2012 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2012) TO (2013);
CREATE TABLE alpha_vantage_db.ohlcv_2013 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2013) TO (2014);
CREATE TABLE alpha_vantage_db.ohlcv_2014 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2014) TO (2015);
CREATE TABLE alpha_vantage_db.ohlcv_2015 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2015) TO (2016);
CREATE TABLE alpha_vantage_db.ohlcv_2016 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2016) TO (2017);
CREATE TABLE alpha_vantage_db.ohlcv_2017 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2017) TO (2018);
CREATE TABLE alpha_vantage_db.ohlcv_2018 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2018) TO (2019);
CREATE TABLE alpha_vantage_db.ohlcv_2019 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2019) TO (2020);
CREATE TABLE alpha_vantage_db.ohlcv_2020 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2020) TO (2021);
CREATE TABLE alpha_vantage_db.ohlcv_2021 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2021) TO (2022);
CREATE TABLE alpha_vantage_db.ohlcv_2022 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2022) TO (2023);
CREATE TABLE alpha_vantage_db.ohlcv_2023 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2023) TO (2024);
CREATE TABLE alpha_vantage_db.ohlcv_2024 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2024) TO (2025);
CREATE TABLE alpha_vantage_db.ohlcv_2025 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2025) TO (2026);
CREATE TABLE alpha_vantage_db.ohlcv_2026 PARTITION OF alpha_vantage_db.ohlcv FOR VALUES FROM (2026) TO (2027);
CREATE TABLE alpha_vantage_db.ohlcv_default PARTITION OF alpha_vantage_db.ohlcv DEFAULT;

COPY alpha_vantage_db.ohlcv
    (
        date,   
        close,
        high,
        low,  
        open,
        volume,
        year,
        stock_id
    )
FROM '/tmp/ohlcv.csv' 
DELIMITER ',' 
CSV HEADER 
NULL '';

-- 1. Balance Sheet
ALTER TABLE alpha_vantage_db.balance_sheet 
    DROP CONSTRAINT IF EXISTS fk_balance_stock;
ALTER TABLE alpha_vantage_db.balance_sheet 
    ADD CONSTRAINT fk_balance_stock FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 2. Cash Flow
ALTER TABLE alpha_vantage_db.cash_flow 
    DROP CONSTRAINT IF EXISTS fk_cashflow_stock;
ALTER TABLE alpha_vantage_db.cash_flow 
    ADD CONSTRAINT fk_cashflow_stock FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 3. Dividends
ALTER TABLE alpha_vantage_db.dividends 
    DROP CONSTRAINT IF EXISTS fk_stock_dividends;
ALTER TABLE alpha_vantage_db.dividends 
    ADD CONSTRAINT fk_stock_dividends FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 4. Earnings
ALTER TABLE alpha_vantage_db.earnings 
    DROP CONSTRAINT IF EXISTS fk_stock_earnings;
ALTER TABLE alpha_vantage_db.earnings 
    ADD CONSTRAINT fk_stock_earnings FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 5. Earnings Estimates
ALTER TABLE alpha_vantage_db.earnings_estimates 
    DROP CONSTRAINT IF EXISTS fk_estimates_stock;
ALTER TABLE alpha_vantage_db.earnings_estimates 
    ADD CONSTRAINT fk_estimates_stock FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 6. Income Statement
ALTER TABLE alpha_vantage_db.income_statement 
    DROP CONSTRAINT IF EXISTS fk_income_stock;
ALTER TABLE alpha_vantage_db.income_statement 
    ADD CONSTRAINT fk_income_stock FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 7. OHLCV
ALTER TABLE alpha_vantage_db.ohlcv 
    DROP CONSTRAINT IF EXISTS fk_ohlcv_stock;
ALTER TABLE alpha_vantage_db.ohlcv 
    ADD CONSTRAINT fk_ohlcv_stock FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 8. Overview
ALTER TABLE alpha_vantage_db.overview 
    DROP CONSTRAINT IF EXISTS fk_stock;
ALTER TABLE alpha_vantage_db.overview 
    ADD CONSTRAINT fk_stock FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 9. Shares Outstanding
ALTER TABLE alpha_vantage_db.shares_outstanding 
    DROP CONSTRAINT IF EXISTS fk_stock_shares;
ALTER TABLE alpha_vantage_db.shares_outstanding 
    ADD CONSTRAINT fk_stock_shares FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 10. Splits
ALTER TABLE alpha_vantage_db.splits 
    DROP CONSTRAINT IF EXISTS fk_Stock_splits;
ALTER TABLE alpha_vantage_db.splits 
    ADD CONSTRAINT fk_Stock_splits FOREIGN KEY (stock_id) 
    REFERENCES alpha_vantage_db.stock(stock_id) ON DELETE CASCADE ON UPDATE CASCADE;

UPDATE alpha_vantage_db.stock 
SET stock_id = 18 
WHERE ticker = 'AIG' AND stock_id = 20;

SELECT setval(
    pg_get_serial_sequence('alpha_vantage_db.stock', 'stock_id'), 
    (SELECT MAX(stock_id) FROM alpha_vantage_db.stock)
);